name: Build and Deploy to Cloud Run

on:
  push:
    tags:
      - 'v*.*.*'
    branches:
      - 'slack'

jobs:
  deploy_on_google_cloudrun:
    runs-on: ubuntu-latest
    name: Deploy Cloud Run
    steps:
    - uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took,pullRequest # selectable (default: repo,message)
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
        if: always() # Pick up events even if the job fails or is canceled.
